development:
  adapter: postgresql
  encoding: unicode
  database: blog_dev
  pool: 5
  username: Dagnis
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: Dagnis
  password:
